name: Djudger

on:
  push:
    branches: [ DT20210403 ]
  pull_request:
    branches: [ DT20210403 ]

jobs:
  run-tests:
    
    runs-on: ubuntu-latest
    timeout-minutes: 15
  
    steps:
    - uses: actions/checkout@v2
      
    - name: Run all tests
      run: |
        echo "run_id : $GITHUB_RUN_ID"
        chmod +x ./startDjudger.sh
        ./startDjudger.sh
      shell: bash
    
