name: Djudger

on:
  push:
    branches: [ main, DpBitmasks, DigitDp, judger ]
  pull_request:
    branches: [ main, DpBitmasks, DigitDp, judger ]

jobs:
  run-tests:
    
    runs-on: ubuntu-latest
    timeout-minutes: 15
  
    steps:
    - uses: actions/checkout@v2
      
    - name: Run all tests
      run: |
        chmod +x Djudger.py
        python3 Djudger.py
      working-directory: ./judger
      shell: bash
    
