name: Djudger

on:
  push:
    branches: [DpBitmasks]
  pull_request:
    branches: [DpBitmasks]

jobs:
  run-tests:
    
    runs-on: ubuntu-latest
    timeout-minutes: 15
  
    steps:
    - uses: actions/checkout@v2
      
    - name: Run all test
      run: |
        chmod +x ./startDjudger.sh
        ./startDjudger.sh
      shell: bash
    
