name: Djudger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    
    runs-on: ubuntu-latest
    timeout-minutes: 15
  
    steps:
    - uses: actions/checkout@v2
      
    - name: Run all tests
      run: |
        echo "HELLO"
      shell: bash
    
